# Generated by Django 5.1.4 on 2025-01-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_order',
            name='sales_order_number',
        ),
    ]
