# Generated by Django 5.1.4 on 2025-01-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_customer_registration_trading_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter_order',
            name='POD_number',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
    ]
