# Generated by Django 5.1.4 on 2025-01-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_rename_offloading_points_route_offloading_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fleet_sales_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('truck_type', models.CharField(max_length=200)),
                ('number_of_trucks', models.IntegerField()),
                ('route', models.CharField(max_length=200)),
                ('UOM', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
