# Generated by Django 5.1.4 on 2025-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_fleet_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='UOM',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='route',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='fleet_sales_order',
            name='truck_type',
            field=models.CharField(max_length=255),
        ),
    ]
