# Generated by Django 5.1.4 on 2025-02-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_fleet_sales_order_uom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fleet_sales_order',
        ),
    ]
