# Generated by Django 5.1.4 on 2025-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_delete_fleet_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='status',
            field=models.CharField(max_length=200, default='Pending'),
        ),
    ]