# Generated by Django 5.1.4 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_sales_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='number_of_trucks_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
