# Generated by Django 5.1.4 on 2025-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_sales_order_number_of_trucks_alocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
