# Generated by Django 5.1.4 on 2025-02-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_sales_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_order',
            old_name='number_of_trucks_alocated',
            new_name='number_of_trucks_allocated',
        ),
    ]
