# Generated by Django 5.1.4 on 2025-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_rename_number_of_trucks_alocated_sales_order_number_of_trucks_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_registration',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='transporter_order',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='transporter_registration',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='truck_type',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
