# Generated by Django 5.1.4 on 2025-02-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_transporter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='linked_order',
        ),
    ]
