# Generated by Django 5.1.4 on 2025-02-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_remove_transporter_order_linked_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.customer_registration'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.products'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.route'),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='transporter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.transporter_registration'),
        ),
    ]
