# Generated by Django 5.1.4 on 2025-02-07 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_sales_order_customer_alter_sales_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='checkpoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_checkpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='POD_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
