# Generated by Django 5.1.4 on 2025-02-07 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_route_checkpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
