# Generated by Django 5.1.4 on 2025-02-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_alter_sales_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
