# Generated by Django 5.1.4 on 2025-02-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_alter_sales_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='sales_order',
            old_name='product',
            new_name='product_id',
        ),
    ]
