# Generated by Django 5.1.4 on 2025-02-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_rename_customer_sales_order_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_order',
            old_name='route',
            new_name='route_id',
        ),
    ]
