# Generated by Django 5.1.4 on 2025-02-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_rename_route_sales_order_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sales_order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales_order',
            old_name='route_id',
            new_name='route',
        ),
    ]
