# Generated by Django 5.1.4 on 2025-02-09 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_rename_customer_id_sales_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='checkpoints',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_checkpoints',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='product',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='route',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='POD_number',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='charge',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='transporter_name',
            field=models.CharField(max_length=200),
        ),
    ]
