# Generated by Django 5.1.4 on 2025-02-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_alter_sales_order_date_alter_sales_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter_order',
            name='pod_file',
            field=models.FileField(blank=True, db_column='POD_File', null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.route'),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.products'),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.route'),
        ),
        migrations.AlterField(
            model_name='transporter_order',
            name='transporter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.transporter_registration'),
        ),
    ]
