# Generated by Django 5.1.4 on 2025-02-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_transporter_order_pod_file_alter_sales_order_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='sales_order_number',
        ),
        migrations.AddField(
            model_name='transporter_order',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.sales_order'),
        ),
    ]
