# Generated by Django 5.1.4 on 2025-02-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_remove_transporter_order_sales_order_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter_order',
            old_name='transporter_name',
            new_name='transporter',
        ),
    ]
