# Generated by Django 5.1.4 on 2025-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_rename_transporter_name_transporter_order_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter_order',
            name='route',
            field=models.CharField(max_length=200),
        ),
    ]
