# Generated by Django 5.1.4 on 2025-02-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_alter_transporter_order_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='pod_file',
        ),
    ]
