# Generated by Django 5.1.4 on 2025-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_remove_transporter_order_pod_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter_order',
            name='pod_file',
            field=models.FileField(blank=True, db_column='POD_File', null=True, upload_to='uploads/'),
        ),
    ]
