# Generated by Django 5.1.4 on 2025-02-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_transporter_order_pod_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='transporter',
        ),
    ]
