# Generated by Django 5.1.4 on 2025-02-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_transporter_order_transporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='sales_order',
        ),
    ]
