# Generated by Django 5.1.4 on 2025-02-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_remove_transporter_order_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter_order',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.sales_order'),
        ),
    ]
