# Generated by Django 5.1.4 on 2025-02-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_transporter_order_sales_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='route',
        ),
    ]
