# Generated by Django 5.1.4 on 2025-02-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_remove_transporter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter_order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.products'),
        ),
    ]
