# Generated by Django 5.1.4 on 2025-02-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_transporter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter_order',
            name='pod_file',
        ),
    ]
