# Generated by Django 5.1.4 on 2025-02-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_remove_transporter_order_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter_order',
            name='transporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.transporter_registration'),
        ),
    ]
